// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button from "./Button.bs.js";

function s(prim) {
  return prim;
}

function reducer(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      return state - 1 | 0;
    } else {
      return state + 1 | 0;
    }
  } else {
    return action._0;
  }
}

function Counter(Props) {
  var initialValue = Props.initialValue;
  var match = React.useReducer(reducer, initialValue);
  var dispatch = match[1];
  var count = match[0];
  var bgColor = count === 0 ? "bg-blue-200" : (
      count > 0 ? "bg-green-200" : "bg-red-200"
    );
  return React.createElement("div", {
              className: "max-w-3xl mx-auto mt-24"
            }, React.createElement("p", {
                  className: "py-4 mb-8 text-center text-4xl " + bgColor
                }, "The count is " + String(count)), React.createElement("div", {
                  className: "flex justify-center"
                }, React.createElement(Button.make, {
                      text: "Increment",
                      className: "border py-2 px-4 bg-gray-200 hover:bg-blue-200 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(dispatch, /* Increment */0);
                        })
                    }), React.createElement(Button.make, {
                      text: "Decrement",
                      className: "border py-2 px-4 bg-gray-200 hover:bg-blue-200 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(dispatch, /* Decrement */1);
                        })
                    }), React.createElement(Button.make, {
                      text: "Reset",
                      className: "border py-2 px-4 bg-gray-200 hover:bg-blue-200 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(dispatch, /* Reset */{
                                      _0: initialValue
                                    });
                        })
                    })));
}

var make = Counter;

export {
  s ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
