// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function Hello(Props) {
  return React.createElement("p", {
              className: "text-center mt-10 text-6xl text-blue-500"
            }, "Hello!");
}

var make = Hello;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
