// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hello from "./Hello.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(Hello.make, {}), root);
}

export {
  
}
/* root Not a pure module */
