// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";

function s(prim) {
  return prim;
}

function Index$Counter(Props) {
  var initialValue = Props.initialValue;
  var match = React.useState(function () {
        return initialValue;
      });
  var setCount = match[1];
  var count = match[0];
  var bgColor = count === 0 ? "bg-blue-200" : (
      count > 0 ? "bg-green-200" : "bg-red-200"
    );
  return React.createElement("div", {
              className: "max-w-3xl mx-auto mt-24"
            }, React.createElement("p", {
                  className: "py-4 mb-8 text-center text-4xl " + bgColor
                }, "The count is " + String(count)), React.createElement("div", {
                  className: "flex justify-center"
                }, React.createElement("button", {
                      className: "border py-2 px-4 bg-gray-200 hover:bg-blue-200 mr-2",
                      onClick: (function (_mouseEvt) {
                          return Curry._1(setCount, (function (x) {
                                        return x + 1 | 0;
                                      }));
                        })
                    }, "Increment"), React.createElement("button", {
                      className: "border py-2 px-4 bg-gray-200 hover:bg-blue-200 mr-2",
                      onClick: (function (_mouseEvt) {
                          return Curry._1(setCount, (function (x) {
                                        return x - 1 | 0;
                                      }));
                        })
                    }, "Decrement"), React.createElement("button", {
                      className: "border py-2 px-4 bg-gray-200 hover:bg-blue-200 mr-2",
                      onClick: (function (_mouseEvt) {
                          return Curry._1(setCount, (function (_x) {
                                        return initialValue;
                                      }));
                        })
                    }, "Reset")));
}

var Counter = {
  make: Index$Counter
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(Index$Counter, {
            initialValue: 0
          }), root);
}

export {
  s ,
  Counter ,
  
}
/* root Not a pure module */
